#
# Works with the .shp files generated by polygons with Microsoft Flight Simulator (MSFS) and exports the bounding box lat and long for each polygon into csvs that can be uploaded to Google My Maps
# Google My Maps has a max limit of 2000 rows per CSV uploaded.
# https://www.google.com/maps/d/u/0/embed?mid=17pRdp7RXoddxQ43SRUQCeIvOmlx8DDMR&ll=39.835351161620224%2C-86.355221&z=7
#

import os

dTop = os.path.join(os.path.join(os.environ['USERPROFILE']), 'Desktop')

def createCsvs():
    allGPSPoints = []

    sf = shapefile.Reader(dTop + "\\IndianaData\\mainpoliesBAK.shp")
    shapes = sf.shapes()

    for s in range(len(shapes)):
        bbox = shapes[s].bbox
        allGPSPoints.append([str(round((bbox[1] + bbox[3])/2,6)),str(round((bbox[0] + bbox[2])/2,6))])

    #Create csv
    import csv

    #2000 item per layer, need to split into different CSVs
    hardCounter = 0

    for i in range(1,5):
        if hardCounter != len(allGPSPoints)-1:
            with open(dTop + "\\IndianaData\\gps"+str(i)+".csv", 'w', newline='') as csvfile:
                writer = csv.writer(csvfile, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
                writer.writerow(['Latitude', 'Longitude'])
                for j in range(hardCounter,len(allGPSPoints)):
                    if j < 1999*i:
                        writer.writerow([(allGPSPoints[j])[0], (allGPSPoints[j])[1]])
                    else:
                        break
                hardCounter = j
    print("CSVs Done")

if __name__ == "__main__":
    #Make backup up file first
    from shutil import copy2
    copy2("G:\\MSFSProjects\\julysfire-indianaMegapack\\PackageSources\\sceneindianaveg\\mainpolies.shp", dTop + "\\IndianaData\\mainpoliesBAK.shp")

    #Read shp file
    import shapefile

    #Call create function
    createCsvs()
